### ISSUE TITLE
ios working, android not working

### ISSUE THREAD

**Issue by abdurrahmanekr** [MattFoley/react-native-stanza-demo#1]
hello @MattFoley , I made the transactions you did in turn. ios worked, but android not worked.
android response is returning null. But when I try fetch it works
ios: 
![simulator screen shot 28 mar 2017 os 2 12 19](https://cloud.githubusercontent.com/assets/15075759/24402653/2cb22088-13c2-11e7-8bf6-d56c0957c716.png)android: 
![screenshot_2017-03-28-14-00-34-694-01](https://cloud.githubusercontent.com/assets/15075759/24402660/318e0eb4-13c2-11e7-864b-9c6958d373f5.jpeg)

What could I have done wrong?

**Comment by abdurrahmanekr** [comment]
Oh @MattFoley, this problem stems from the XMLHttpRequest header. A simple example:
```javascript
var request = new XMLHttpRequest();
request.onreadystatechange = (e) => {
  if (request.readyState !== 4) {
    return;
  }

  if (request.status === 200) {
    console.log('success', request.responseText);
  } else {
    debugger;
    console.warn('error');
  }
};

request.open('POST', 'http://www.example.com/http-bind/');
request.send('<body hold="1" rid="9211032549" to="www.example.com" ver="1.6" wait="30" xml:lang="en" xmlns="http://jabber.org/protocol/httpbind" xmlns:xmpp="urn:xmpp:xbosh" xmpp:version="1.0"></body>');
```
Result: error
error: **payload is set but no content-type header specified**
What can I do now?

**Comment by MattFoley** [comment]
@abdurrahmanekr I am really not sure, this works for my setup on Android. If you do figure out your issue, definitely post it here for anyone else who runs into a similar problem.

**Comment by abdurrahmanekr** [comment]
@MattFoley [In this link](https://github.com/facebook/react-native/blob/bc74dd1e14372ce2ff7c6d21401e67c946eb7595/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java#L241) line:241, there is a "**payload is set and no content-type header specified**" blocking for android. But not for iOS. Is this something that react-native needs to fix? Or stanza.io?
Did you run the application on http-bind?

**Comment by czorn** [comment]
The fix for this is to modify this file ../stanza.io/lib/transports/bosh.js around line 245 and adding the content type header:

```
    {
        uri: self.url,
        body: body,
        method: 'POST',
        strictSSL: true,
        headers: {
            'Content-Type': 'text/xml'
        }
    },

**Comment by abdurrahmanekr** [comment]
Thank you @czorn ❤️ 
[pull request](https://github.com/legastero/stanza.io/pull/206)

**Comment by MattFoley** [comment]
Ah, sorry about that. I'm strictly using web sockets, not Bosh.
